from __future__ import annotations

from typing import Protocol

from ym_bridge.models import PlayerState


class MusicProvider(Protocol):
    async def fetch_state(self) -> PlayerState: ...

    async def play(self) -> None: ...

    async def pause(self) -> None: ...

    async def play_pause(self) -> None: ...

    async def stop(self) -> None: ...

    async def next(self) -> None: ...

    async def previous(self) -> None: ...

    async def seek(self, offset_us: int) -> None: ...

    async def set_position(self, track_id: str, position_us: int) -> None: ...

    async def set_volume(self, volume: float) -> None: ...

    async def like_current(self) -> None: ...

    async def dislike_current(self) -> None: ...

    async def set_rotor_seeds(self, seeds: tuple[str, ...]) -> None: ...

    def get_rotor_seeds(self) -> tuple[str, ...]: ...

    async def close(self) -> None: ...
